%YAML:1.0
---
model_type: PINHOLE
image_width: 1280
image_height: 560

distortion_parameters:
   k1: -5.6143027800000002e-02
   k2: 1.3952563200000001e-01
   p1: -1.2155906999999999e-03
   p2: -9.7281389999999998e-04
projection_parameters:
   fx: 7.7537235550066748e+02
   fy: 7.7537235550066748e+02
   cx: 6.1947309112548828e+02
   cy: 2.5718049049377441e+02
