%YAML:1.0
---
model_type: PINHOLE
image_width: 1280
image_height: 560

distortion_parameters:
   k1: -5.4921981799999998e-02
   k2: 1.4243657430000001e-01
   p1: 7.5412299999999996e-05
   p2: -6.7560530000000001e-04
projection_parameters:
   fx: 7.7537235550066748e+02
   fy: 7.7537235550066748e+02
   cx: 6.1947309112548828e+02
   cy: 2.5718049049377441e+02

