%YAML:1.0
---
imuFreq: 200
imageFreq: 30
simStart: 0
simEnd: 2
gyr_noise_sigma: 0.0001
acc_noise_sigma: 0.001
gyr_bias_sigma: 0.00001
acc_bias_sigma: 0.0001
pixel_noise: 2
add_pixel_noise: 0
camera_yaml: "/home/kdq/Workspace/SLAM-KDQ/SlamCodes/vo_initialization/config/cam0_pinhole.yaml"

Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-1.0,  0.,  0.,  0.,
          0.0, 1.0,  0., 0.1,
           0.,  0.,-1.0, 0.2,
           0.,  0.,  0., 1.0]


SimModel: !!opencv-matrix
  rows: 3
  cols: 6
  dt: d
  data: [0.2, 0.5, 0.0, 10.0, 0.5, 0.0,
         0.2, 0.5, 0.0, 5.0, 0.5, 0.0,
         1.2, 0.7854, 0.2, 0.0,0.075,0.0]
